### ISSUE TITLE
Bug in column iteration for `Tables.columns(Tables.table(m::AbstractMatrix))`

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/Tables.jl#125]
I think there is a bug in `table(m::AbstracMatrix)`

```
nt = (a = [1, 2], b = [3, 4]
tt = Tables.table([1 2; 3 4])
for col in Tables.columns(nt)
    @show col[1]
end #works, great
for col in Tables.columns(tt)
    @show col[1]
end #does not work
```

It errors because in the second one col is of a weird type.

```
col = Tables.MatrixRow{Array{Int64,2}}(1, Tables.MatrixTable{Array{Int64,2}}(Symbol[:Column1, :Column2], Dict(:Column2 => 2,:Column1 => 1), [1 2; 3 4]))
```
I would think that Tables.columns would iterate through vectors. But its not doing that and I'm not sure why.

**Comment by quinnj** [comment]
Sorry for the slow response here; not sure how this slipped through the cracks. The issue here is that "column iteration" isn't part of the Tables.jl `Tables.columns` interface. You are required to return a `Columns` object from `Tables.columns`, which is any object that supports `getproperty` (soon to be `getcolumn`), and `propertynames` (soon to be `columnnames`). Tables.jl does provide the `Tables.eachcolumn(columns)` convenience function for iterating over columns.
