### ISSUE TITLE
API clarification request: space/time complexity of `rows(table)` and `columns(table)`

### ISSUE THREAD

**Issue by tkf** [JuliaData/Tables.jl#135]
Does `Tables.rowaccess(table) == true`/`Tables.columnaccess(table) == true` mean `Tables.rows(table)`/`Tables.columns(table)` is O(1) (with reasonably small constant)?  Current documentation is not super clear about this aspect:

https://github.com/JuliaData/Tables.jl/blob/59de960813431f3559e9652d3508d8f6f9592913/README.md#L60

https://github.com/JuliaData/Tables.jl/blob/59de960813431f3559e9652d3508d8f6f9592913/README.md#L66

(This is something I noticed while looking at #131. But I just realized that this already existed before that PR.)

**Comment by quinnj** [comment]
As far as I'm aware of various implementations of `Tables.rows`/`Tables.columns`, yes, this is a O(1) operation. I'm not exactly clear on the request here: that it be _required_ as part of the API that it be O(1)? Or that it just mention when implementing that it should be? It kind of naturally falls out of the definition that if you define `Tables.rowaccess`/`Tables.columnaccess`, then your provided `Tables.rows`/`Tables.columns` functions will usually just return the input object (since the interface functions tend to be implemented on the table type itself); the other common case is when you have some kind of wrapper/lazy operation object, which may just return the wrapped table.

**Comment by tkf** [comment]
Yes, it'd be nice to mention that the `Tables.rows(table)` and `Tables.columns(table)` must be O(1) when the corresponding `Tables.rowaccess(table)` and `Tables.columnaccess(table)` are defined to be `true`.

I agree it's natural but I thought it'd be nice to clarify it.  Someone may implement `Tables.columns` that is better than the fallback but still copies the data.
