### ISSUE TITLE
Add `NamedTuple(::Tables.Row)` method?

### ISSUE THREAD

**Issue by ssfrr** [JuliaData/Tables.jl#154]
I frequently work with `Vector{NamedTuple}` as a nice built-in table type. So when using CSV.jl I want to easily convert each `Row` to a `NamedTuple`. Would it make sense to have a `NamedTuple(::Tables.Row)` constructor defined? Then I could do things like:

```julia
    map(CSV.File(joinpath(datadir, "clip_metadata.csv"))) do r
        dir = joinpath("/home/sfr/soundfield_resynth", r.series)
        merge(NamedTuple(r), (filename=joinpath(dir, r.filename),))
    end
```

Without needing to pull in `Tables.jl` as a direct dependency. Currently  it seems the best solution is to add a `using Tables` and change my `map` to be `map(Tables.namedtupleiterator(CSV.File(joinpath(datadir, "clip_metadata.csv")))) do r`, which feels pretty wordy.

**Comment by quinnj** [comment]
Yeah, `Tables.namedtupleiterator` is one solution, but another new thing in the 1.0 release is `Tables.Row`, which you could use like:
```julia
map(CSV.File()) do r
    row = Tables.Row(r)
    # do stuff w/ row which now acts like a NamedTuple
end
```
So one extra step still, but `Tables.Row` was designed with all the same methods as NamedTuple, so it should act as one in every respect.

The biggest challenge with having `NamedTuple(r)` is making it efficient, which is why `Tables.Row` was introduced. `Tables.Row` is just a wrapper struct that provides NamedTuple behavior, but will just "pass through" any efficiency of the underlying row, including type-stable field access, constant prop, etc. But just calling `NamedTuple(r)` doesn't have enough type information (provided from the Tables.jl interface definitions or otherwise) to make generating a NamedTuple efficient. `Tables.namedtupleiterator` works because it can query the input table schema upfront and then iterating NamedTuples is efficient; trying to do `NamedTuple(r)` would be incurring that "schema query" cost on each iteration.

And now that I think about it, one thing definition we should have is `Tables.Row(nt::NamedTuple) = nt`; i.e. if your row is already a NamedTuple, we don't need to wrap it for NamedTuple behavior.

**Comment by ssfrr** [comment]
Oh, whoops, I thought that each element `CSV.File` iterated was already a `Tables.Row`, but in re-reading the docs I see it says they're a `CSV.Row`, not a `Tables.Row`.

It doesn't look like `Tables.Row` supports `merge`:

```julia
merge(Tables.Row((a=1, b=2)), (c=3,))
# MethodError: no method matching merge(::Tables.Row{NamedTuple{(:a, :b),Tuple{Int64,Int64}}}, ::NamedTuple{(:c,),Tuple{Int64}})
```

For most of my work I'm only working with at most a few thousand rows, and often only a few dozen, so efficiency isn't very important to me. Generally I try to get things into NamedTuples as early as possible so things are more uniform, though I get that you might not want to leave performance traps around that will hurt folks with more stringent performance needs.

**Comment by quinnj** [comment]
Yeah, the issue w/ having `merge` is that our `AbstractRow`/`Row` definitions in Tables.jl are wrapper types/interfaces, i.e. they always need to have some underlying "source" row, but we don't know how to make one. That makes having something like `merge` or `structdiff` or other mutable-ish operations difficult since we don't know how to make a new "row" for those operations.

Adding a `NamedTuple` constructor for any `AbstractRow` though is pretty easy, so I did that [here](https://github.com/JuliaData/Tables.jl/pull/157). Note that we need to define it only on `AbstractRow`, to not pirate any definitions from Base. That means you'd need to do:
```julia
for row in Tables.rows(tbl)
    nt = NamedTuple(Tables.Row(row))
    # now do stuff w/ nt, which is a NamedTuple
end
```
i.e. wrap the row in `Tables.Row` first to ensure it's an object that actually subtypes `AbstractRow` and then convert to `NamedTuple`. Alternatively, we could have a `rowtonamedtuple` function that was specific to Tables.jl converting a "row" to a NamedTuple.
