### ISSUE TITLE
Copying in matrix(table(A)) when A is a matrix

### ISSUE THREAD

**Issue by ablaom** [JuliaData/Tables.jl#182]
I was expecting that if `A` is a matrix and I do `t = table(A)` then `matrix(t)` just unwraps `A`, ie no copying.  But evidently this is not the case:

```julia
julia> A = [1 2; 2 4]
2×2 Array{Int64,2}:
 1  2
 2  4

julia> a = Tables.matrix(Tables.table(A))
2×2 Array{Int64,2}:
 1  2
 2  4

julia> A[1, 1] = 10_000
10000

julia> a
2×2 Array{Int64,2}:
 1  2
 2  4
```

Is there a reason for wanting this behaviour?

**Comment by ablaom** [comment]
Our use case for different behaviour: https://github.com/alan-turing-institute/MLJBase.jl/issues/309#issuecomment-646327098

**Comment by quinnj** [comment]
Yeah, currently we [always create a new matrix](https://github.com/JuliaData/Tables.jl/blob/335515e7474b739b35aadf3fcf375e45d2ed4438/src/matrix.jl#L73) for `Tables.matrix`. It was implemented this way just because we needed to generically create a matrix for any table input. We could add a special-case definition like `Tables.matrix(mt::MatrixTable) = mt.matrix` if you want to do a PR + a quick test

**Comment by tpapp** [comment]
I would prefer that we always create a new, independent matrix. That allows the use of `!` methods in LinearAlgebra without special-casing.

**Comment by OkonSamuel** [comment]
@tpapp  But in the case of a `MatrixTable` i think it's better to just give the original Matrix especially if the `MatrixTable` wraps a `SparseMatrix`. By the way am hoping Tables.jl add better support for Sparse data
