### ISSUE TITLE
Ability to find out which format (row or column) is native to the table

### ISSUE THREAD

**Issue by waralex** [JuliaData/Tables.jl#201]
The problem is that if the table defines both `rowaccess` and `columaccess`, then there is no way to find in what format data is stored initially in the table, more generally, there is no way to find out which format is more efficient for concrete table. This is important because it is often possible to develop efficient algorithms for both row and column input data, but it is not clear which one to choose if the input data supports both interfaces.

**Comment by quinnj** [comment]
This is by design. Take an example sink function like `CSV.write`; to write a csv file, it ultimately needs to write out a table row by row. If the input table is row-oriented, that's great, it just iterates the input table rows and writes out the delimited lines. If the input table is column oriented (e.g. a DataFrame), then what would be ideal? Well, it'd be great to have a sort of "row view iterator" over the DataFrame. The point is, it actually doesn't matter what orientation the input table is, the _sink_ function almost _always_ has a preference in terms of which way it'd needs/wants the data oriented. That's why with Tables.jl, you don't worry about the orientation of the input table, but call `Tables.rows(input)` or `Tables.columns(input)` depending on which orientation _you need_ when working with tables, knowing that even if the input table is oppositely-oriented, Tables.jl itself provides the most efficient fallback to transform between (i.e. a default "row view iterator" for column-oriented inputs, and a "column builder" for row-oriented inputs).

So I'd suggest looking at your use-case and asking the question: "What's the ideal orientation I could be working with?" and use that. Happy to talk through more details if you explain the specific use-case.

**Comment by waralex** [comment]
A simplified, but typical example - I need to get in column form the first `n` rows from a large table. If the original table is a column table, it is easiest to get them as columns slices. However, if the original table is a row table with an additional `columnaccess` interface, it is easier to read rows, otherwise everything depends on the specific implementation in the table. For example, it can completely materialize columns in memory and thus cause a lot of unnecessary allocations. 

For example, if data is stored in a file line by line, then such a table may have a column interface for the convenience of some users, but at `getcolumns` call it will at least have to find all the line separators in the file to find out the number of rows (the existence of `length(col)` is the interface requirement). And if I only need the first 100 entries out of 10^6 entries in each column, then it is much more profitable for me to read the rows, although I can't find out about it from the interface.

I may be overcomplicating, or have very specific tasks. So if you think that this is a rare or strange case, then you may be right.

**Comment by waralex** [comment]
By the way, why such a strict requirement for columns "retrieved column must be an indexable collection with known length"? It seems to me that for columns, as opposed to rows, it is enough just to be iterable.

**Comment by waralex** [comment]
@quinnj 
> That's why with Tables.jl, you don't worry about the orientation of the input table, but call Tables.rows(input) or Tables.columns(input) depending on which orientation you need when working with tables, knowing that even if the input table is oppositely-oriented, Tables.jl itself provides the most efficient fallback to transform between (i.e. a default "row view iterator" for column-oriented inputs, and a "column builder" for row-oriented inputs).

Real example. ClickHouse integration with Tables. At inserting I want to send data in blocks of columns with maximum 100,000 elements in each column. It is convenient to use `Tables.columns`, but the incoming data can be huge in size and for the default implementation of `Tables.columns` for the original rows table may simply not have enough memory. Does this mean that I should always use `Tables.rows`, because the performance drawdown in the case of initially columns tables is less evil than not being able to insert in the case of large rows tables?

**Comment by tpapp** [comment]
I don't think that leaving the determination of the orientation to the *sink* is able to select the most efficient way in general.

Consider a sink that takes 1s for row and 10s for column orientation, and a source that takes 100s for row and 10s for column access. The sink would go for row with the way Tables.jl works currently (101s), while column access would be more efficient (11s).

Also "native" is a misleading term in this context. It is better to think in terms of various trade-offs wrt CPU and memory requirements; eg for a matrix in memory columns are "native" but rows are cheap to, while for a huge CSV file columnswise access may take prohibitive amounts of RAM. Designing an API for this is not an easy task though.

**Comment by waralex** [comment]
>It is better to think in terms of various trade-offs wrt CPU and memory requirements; eg for a matrix in memory columns are "native" but rows are cheap to, while for a huge CSV file columnswise access may take prohibitive amounts of RAM. Designing an API for this is not an easy task though.

The problem is that `Tables.rows` returns a forward iterator according to the interface, however, the column according to the interface is a random access iterator. It is much more difficult to implement such an iterator without full materialization in memory than a forward iterator. 
Therefore, it looks like a client that streams incoming data should use `Tables.rows`, regardless of its internal architecture, because using `Tables.columns` simply most likely will not allow processing the amount of data that does not fit in RAM. Even if the source can read/generate rows streamwise, it is very likely that using `Tables.columns` will lead to materialization of all data in memory.

**Comment by quinnj** [comment]
> By the way, why such a strict requirement for columns "retrieved column must be an indexable collection with known length"? It seems to me that for columns, as opposed to rows, it is enough just to be iterable.

The requirement was actually just iterable pre-1.0, but in implementations, it turned out to be more inconvenient to work with and some sinks just assumed indexable + known length anyway. There weren't any real use-cases people could vouch for, so the additional requirement of indexable + known length was added.

> At inserting I want to send data in blocks of columns with maximum 100,000 elements in each column.

In a new imminent release, there's a [`Tables.partitions`](https://juliadata.github.io/Tables.jl/dev/#Tables.partitions) function that will allow sources to produce iterable "tables" if they have natural partitions. Several sources (CSV.jl, Arrow.jl, ODBC.jl, JuliaDB.jl) naturally have internal "chunks" and sinks will be able to leverage these natural partitions. A natural extension of this would be to have a `partitioning` function that took any input table and "chunked" it up in N number of rows. I think the interface allows for lots of these kinds of extensions and additions without requiring any more from the API.

> I don't think that leaving the determination of the orientation to the sink is able to select the most efficient way in general.

Maaaybe, but again, I'll always come back to the point that almost every sink I'm aware of has a "natural" orientation that it _wants_ the data, and in many cases, _requires_ the data; so what's the alternative: it doesn't accept other-oriented inputs because it might be less efficient? In my experience, people would rather things "just work", and those who are really concerned with efficiency/performance will hand-tune things to ensure optimizations anyway. 

> Therefore, it looks like a client that streams incoming data should use Tables.rows, regardless of its internal architecture,

I disagree; DataFrames.jl, for example, is an "in memory" table type, so it has a natural limitation of requiring things to fit in memory anyway, so it's extremely convenient to be able to call `Tables.columns(input)` and that's basically it for converting _any_ table-like input into a DataFrame. And there are various optimizations like mmapping columns that can even enable larger-than-RAM datasets to work seamlessly in a DataFrame.

That said, `Tables.partitions` was introduced specifically so that tables could provide smaller chunks of themselves to sinks in order to reduce the need, in most cases, of running out of RAM.

**Comment by waralex** [comment]
> DataFrames.jl, for example, is an "in memory" table type, so it has a natural limitation of requiring things to fit in memory anyway, so it's extremely convenient to be able to call Tables.columns(input) and that's basically it for converting any table-like input into a DataFrame.

I do not dispute that for DataFrames columns are convenient. I was talking about a receiver that does not have the condition that it is inmemory and that expects that the input can be both column `DataFrames` and huge volumes of rows data, for example, from a file. The problem is that there are no different behind the interface and it is impossible to understand whether it is possible to use columns in concrete input. Yes, it is possible that `partitions` can help.

>it doesn't accept other-oriented inputs because it might be less efficient? In my experience, people would rather things "just work", and those who are really concerned with efficiency/performance will hand-tune things to ensure optimizations anyway.

From my point of view, the problem is that the conversion between formats is assigned to the source, and the recipient cannot find out whether using a specific interface method will cause materialization, etc. It would seem to me a more logical approach when the source implements one type of interface (the table can be either rows or columns) and there are explicit conversion functions from one type to another that the recipient can consciously call.

Now the situation is similar to the following. Suppose we have an `Iteratable` interface with methods `get_forward` (returns iterator) and `get_random_access` (returns vector) and the receiver can't know whether the source object is a vector or an iterator. Yes, using `get_random_access` is convenient in any case and it will work, but it will mean materializing data from the iterator if the source object is an iterator. And it would be nice for the client to consciously cause such a materialization, rather than having it implicitly.

**Comment by quinnj** [comment]
> And it would be nice for the client to consciously cause such a materialization, rather than having it implicitly.

I can understand this feeling, but in practice, it's too annoying for users. Most of the time, people want things to "just work" and they can optimize later.

That said, there is certainly a way for sinks to "enforce" an orientation; you just do something like:
```julia
function sink(input)
    @assert Tables.columnaccess(input)
    cols = Tables.columns(input)
    # ...
end
```
in this way, only inputs that are _already_ columnar are allowed, and if a user wants to pass a row-oriented input table, they would need to call `sink(Tables.columns(rows))` themselves, which, as you mentioned, puts the materialization burden on the user instead.

**Comment by tpapp** [comment]
> almost every sink I'm aware of has a "natural" orientation that it wants the data, and in many cases, requires the data [...] That said, Tables.partitions was introduced specifically so that tables could provide smaller chunks of themselves to sinks in order to reduce the need, in most cases, of running out of RAM.

Yes, I agree with this. `Tables.partitions` may solve this problem in practice in a nice way.

**Comment by quinnj** [comment]
In the end, I'd turn the question back on the use-case: if you actually knew the orientation of the input, what would you actually do different? In all the cases I'm aware of, the answer is: I'd still use `Tables.rows` or `Tables.columns` because of x, y, and z. In @waralex's case, it's pretty clear that `Tables.rows` should be used since there's row limits to abide by and memory concerns of materializing huge tables. `Tables.rows` is _the_ way to support "streaming" scenarios, along with `Tables.partitions` in order to potentially multithread "chunk processing".
