### ISSUE TITLE
Interface specification in documentation

### ISSUE THREAD

**Issue by mtsch** [JuliaData/Tables.jl#205]
Today, I started implementing my first Tables interface. At first, I implemented everything as `trait(::MyType)` instead of `trait(::Type{<:MyType})` and was pretty confused when some things kinda half-worked (`MyType` just happens to also be an array).

I think the docs could be clearer about the fact that you need to implement the interfaces on the types, not the values. Maybe the interface table could show things like `Tables.istable(::Type{<:table})` or `Tables.istable(table_type)` instead of `Tables.istable(table)`.

I can create a PR that attempts to fix that, but I wanted to get some feedback first. Maybe I was just being sloppy when reading the docs.

**Comment by quinnj** [comment]
Technically, you _should_ be able to call the traits on _instances_; what didn't work for you? It's recommended to define the traits for your type on the type itself, since that will generally lead to more efficient code, but in some cases, it might be based on a runtime property. It's the job of the sink to call the trait functions on instances instead of types, but I'm sure there are some out there that don't.

**Comment by mtsch** [comment]
Sorry, I must have messed something up. I distinctly remember defining things in terms of types helped, but I probably fixed something else along the way.

I can't reproduce my example anymore and looking at the Tables source code, there doesn't seem to be a way I could. Closed.
