### ISSUE TITLE
default propertynames/getproperty and columnnames/getcolumn definitions for AbstractRow are mutually recursive

### ISSUE THREAD

**Issue by jrevels** [JuliaData/Tables.jl#221]
This might just be a documentation issue (or I could've missed something), but:

```jl
julia> struct Foo <: Tables.AbstractRow
           x::Int
       end

julia> propertynames(Foo(1))
ERROR: StackOverflowError:
Stacktrace:
 [1] propertynames(::Foo) at /Users/jarrettrevels/.julia/dev/Tables/src/Tables.jl:167
 [2] columnnames(::Foo) at /Users/jarrettrevels/.julia/dev/Tables/src/Tables.jl:105
 ... (the last 2 lines are repeated 39990 more times)
 [79983] propertynames(::Foo) at /Users/jarrettrevels/.julia/dev/Tables/src/Tables.jl:167

julia> Tables.columnnames(Foo(1))
ERROR: StackOverflowError:
Stacktrace:
 [1] columnnames(::Foo) at /Users/jarrettrevels/.julia/dev/Tables/src/Tables.jl:105
 [2] propertynames(::Foo) at /Users/jarrettrevels/.julia/dev/Tables/src/Tables.jl:167
 ... (the last 2 lines are repeated 39990 more times)
 [79983] columnnames(::Foo) at /Users/jarrettrevels/.julia/dev/Tables/src/Tables.jl:105
```

ref https://github.com/JuliaData/Tables.jl/blob/fdf4d114bbca31e547c18cde9c18ff84ac093e09/src/Tables.jl#L105

ref https://github.com/JuliaData/Tables.jl/blob/fdf4d114bbca31e547c18cde9c18ff84ac093e09/src/Tables.jl#L167

We can fix either by breaking the mutual recursion (e.g. delete the `propertynames(::RorC)` overload) or by documenting that one of these two functions *must* be overloaded by new `AbstractRow` subtypes. I'm a Tables newcomer, so I'm unsure which approach is preferred (I'm assuming the latter?). I'm guessing a similar issue exists for AbstractColumns but haven't checked.

EDIT:

> documenting that one of these two functions *must* be overloaded by new `AbstractRow` subtypes

`getcolumn` etc is under "Required Methods" in the docs, but I interpret that in combo with "Default Definition"  to mean "this method needs to be defined *somewhere*; if the default definition seems good, then you're good to go"

**Comment by jrevels** [comment]
Looks like this also applies to property/column access:

```
julia> getproperty(Foo(1), :x)
ERROR: StackOverflowError:
Stacktrace:
 [1] getcolumn(::Foo, ::Symbol) at /Users/jarrettrevels/.julia/dev/Tables/src/Tables.jl:94
 [2] getproperty(::Foo, ::Symbol) at /Users/jarrettrevels/.julia/dev/Tables/src/Tables.jl:165
 ... (the last 2 lines are repeated 39990 more times)
 [79983] getcolumn(::Foo, ::Symbol) at /Users/jarrettrevels/.julia/dev/Tables/src/Tables.jl:94
```

**Comment by quinnj** [comment]
Yes, we should update the docs; specifically if you do subtype `Tables.AbstractRow`, then you shouldn't rely on the default definitions, but should overload `Tables.getcolumn` and `Tables.columnnames`.

In my mind, when I'm implementing Tables.jl somewhere, I naturally gravitate towards _always_ defining `Tables.getcolumn` and `Tables.columnnames` because it's "safer"; i.e. they're not going to clash with any other accidental definitions (like if I implement `getproperty` or something), and they ensure everything Tables.jl-wise will "just work". And if I'm subtyping `AbstractRow`, it ensures that all the other convenient behavior "just works" too. It's the "neck" of the interface hourglass because it's just 3 simple definitions:
```julia
Tables.getcolumn(r::MyRow, i::Int) = ...
Tables.getcolumn(r::MyRow, nm::Symbol) = ...
Tables.columnnames(r::MyRow) = ...
```
and boom, everything else will just work. The default definitions are really just there to allow treating naive objects as valid "rows", like NamedTuples and generators of custom structs.
