### ISSUE TITLE
Tables.jl user use cases benefiting from Tables.schema implementation ?

### ISSUE THREAD

**Issue by mathieu17g** [JuliaData/Tables.jl#245]
Hello,

I can't find an interface user example which would benefit from an implementation of `Tables.schema` returning a `Tables.Schema`  in ArchGDAL.jl Tables interface, compared to letting [`buildcolumns(::Nothing, rowitr::T) where {T}`](https://github.com/JuliaData/Tables.jl/blob/main/src/fallbacks.jl#L198-L218) in Tables.jl/fallback.jl build one.  
For messy data, it seems difficult to do it faster than the implementation already available in Tables.jl/fallback.jl and Tables.jl/utils.jl.

The only case I see, is where an interface user would benefit from calling `Tables.schema` before calling `Tables.columns` or `Tables.rows`

Could you please point: 
- to such use cases if there are any you are aware of, or 
- to more detail information/discussion on the benefit of implementing a `Tables.schema` function returning a `Tables.Schema` ?

**Comment by quinnj** [comment]
You are correct that for messy data, it's often best to leave the definition as `Tables.schema(x::MyTable) = nothing)`. But there are plenty of cases where having a schema is well-defined: for [`CSV.File`](https://github.com/JuliaData/CSV.jl/blob/main/src/file.jl#L67), it parses the entire file and detects all column types before returning the `CSV.File` object that has a fixed set of column names/types; similarly for [`Arrow.Table`](https://github.com/JuliaData/Arrow.jl/blob/main/src/table.jl#L202), the schema is encoded in the arrow file metadata itself, so we just expose that to users when using arrow data as a table.

On the other hand, [`SQLite.Query`](https://github.com/JuliaDatabases/SQLite.jl/blob/master/src/tables.jl#L25) relies on `nothing` for the schema since the database doesn't make any hard guarantees that values follow a column type. It's also not reliable to know if a column will have missing values or not, so it's best to just leave the schema as `nothing`.

**Comment by mathieu17g** [comment]
Thank you for your quick answer. 

I guess that it was more worth doing the cleaning in CSV.jl since they are doing it from scratch compared to ArchGDAL which relies on GDAL/OGR and it’s drivers. 

I will suggest to ArchGDAL developers to take the the return nothing option and keep the enhancement of developing a detailed Tables.Schema construction for once they will have fully settled on the types hierarchy of geometries. 

Mathieu
