### ISSUE TITLE
Better default for Tables.columnnames

### ISSUE THREAD

**Issue by juliohm** [JuliaData/Tables.jl#247]
The current default is `propertynames` and it doesn't work for custom **row** tables.

**Comment by juliohm** [comment]
Maybe something along the lines of:

```julia
function columnnames(table)
  if rowaccess(table)
    table |> columns |> columnnames
  else
    table |> rows |> columnnames
  end
end
```

**Comment by quinnj** [comment]
It can be expensive and not necessarily idempotent to call `columns` or `rows` on a source, so those aren't really options for getting the column names. I mean, the default fallback isn't going to work in call cases; that's why custom row tables should overload it specifically for their type. If you have an extended example of an issue, then I'm happy to help figure out the best way forward.

**Comment by bkamins** [comment]
> that's why custom row tables should overload it specifically for their type

This is what I would also assume that should be done.

**Comment by juliohm** [comment]
Got it. So users are expected to specialize Tables.columnnames even when they implement the row-table pattern. Perhaps this could be added to the docs then? I am happy to submit a PR if that is desirable, the only issue is that I am not a native English speaker so the text may not be ideal.

**Comment by nalimilan** [comment]
I'd say make a PR and others can make suggestions if needed.

**Comment by quinnj** [comment]
> So users are expected to specialize Tables.columnnames even when they implement the row-table pattern

No, this isn't expected. Let's clarify the roles of people here: table _authors_ vs. table _users_. The _author_ is the person creating the table type and is concerned with how to properly implement the Tables.jl interface; the _user_ uses the table type and may or may not expect certain functionality.

In terms of the Tables.jl API, let's make it clear what should be implemented and how it can be used:
  * If your table is row-oriented, it should overload `Tables.istable`, `Tables.rowaccess` and `Tables.rows`
  * For whatever object is returned from `Tables.rows(your_tbl)`, it must iterate "rows" where each row satisfies the `AbstractRow` interface (implements `Tables.columnnames`, `Tables.getcolumn`)
  * Optionally, you can also implement `Tables.schema` on the object returned from `Tables.rows(your_tbl)` if that's a well-defined concept for your table

That's it. That's all that's expected from table _authors_ in terms of implementing the Tables.jl interface correctly.

For _users_ then, the pattern really follows what we've outlined above:
  * Can call `Tables.rows(your_tbl)` _or_ `Tables.columns(your_tbl)`; calling `rows` returns the object the author implemented above; calling `columns` will hit a generic fallback in Tables.jl package that will turn the return object of `rows(your_tbl)` into a valid "columns" object
  * On the returned object from `Tables.rows`, they can calll `Tables.schema` to see if a schema exists (if `nothing` is returned, there is no schema
  * Otherwise, they can just iterate the returned row-iterator object and process table rows

So note that being able to call `Tables.columnnames` on any table object or on the result of `Tables.rows` is not expected. I can call:
```julia
r = Tables.rows(x)
sch = Tables.schema(r)
if sch !== nothing
    nms = sch.names
end
```
to get the potential column names of a row-oriented table. Otherwise, the column names aren't guaranteed to be available until I start iterating rows, wherein I can call `Tables.columnnames(row)` on each row of the row-oriented table.

Hopefully this all helps clarify the expected API implementation/usage? I should definitely do another pass over the docs and try to clarify things some more.

I know it can sometimes feel a little restrictive in terms of what you can _do_ with the Tables.jl interface, but keep the following in mind:
  * We're trying to create a _simple_ API that can be satisfied by all sorts of table-like things
  * We're trying to keep the API surface area as _small as possible_ to help with the desired simplicity
 Notice in those 2 bullet points that we're _NOT_ trying to make the Tables.jl API super easy to use for the common/casual user. It's kind of expected that _using_ the Tables.jl API is somewhat of an advanced-user task wherein they need to understand the requirements, expectations, etc. This is in contrast to say, the DataFrames.jl API, where we _do_ expect casual/common users to be bumping into things or trying operations out all the time in possibly unexpected ways. The rigidity of the Tables.jl API is currently part of the focus on keeping the API as generic and simple as possible.

**Comment by juliohm** [comment]
Makes sense @quinnj , thanks for the detailed explanation. I will close the issue.
