### ISSUE TITLE
Support `Generator` as a possible table?

### ISSUE THREAD

**Issue by andyferris** [JuliaData/Tables.jl#30]
It seems to me that a `Base.Generator` which happens to stream rows of `NamedTuple`s (with the same field names) would be a good candidate for being a "table".

Basically, I would like to type things like `columntable(row for row in other_table)`, and similarly for `TypedTables.Table` constructors, etc. Does that seem reasonable?

`Generator`s are a bit strange in that they may or may-not have a size, and may or may-not have a "default" eltype that can be computed in the case of an empty iterator. I'm not sure if we handle empty cases in a similar vein to `collect(::Generator)`?

**Comment by davidanthoff** [comment]
Generators never have an element type, as far as I understand it (see [here](https://github.com/JuliaLang/julia/blob/1c6f89f04a1ee4eba8380419a2b01426e84f52aa/base/generator.jl#L126)), so you can never determine based on the type whether a generator is a table or not. You need to iterate it and look at the elements you get to decide that, and I think that means that the ``Tables.istable`` trait will have to return ``false`` always in those cases.

[TableTraits.jl](https://github.com/queryverse/TableTraits.jl) handles this case, though, and if you implement the [kind of constructor that DataFrames.jl](https://github.com/JuliaData/DataFrames.jl/blob/2d6476a66797112acfc2e992df13afbab107685c/src/other/tables.jl#L15) has it will just work (your code example works with ``DataFrame``). Doing that would be good in any case because then you can also consume all the other queryverse sources.

The way [TableTraits.jl](https://github.com/queryverse/TableTraits.jl) handles this is that its trait function ``isiterabletable`` can return ``missing``, specifically for situations like this one here where one cannot determine whether something is a table or not based on the type alone. The constructor code in ``DataFrame`` then handles that case properly [here](https://github.com/JuliaData/DataFrames.jl/blob/2d6476a66797112acfc2e992df13afbab107685c/src/other/tables.jl#L24).

**Comment by quinnj** [comment]
I think we should be fine to handle this case in Tables.jl; we already know that Generators iterate, so the other assumption is that a particular Generator iterates PropertyAccessible objects, which will be true for all but `primitive type` objects. If someone tries to iterate Int64s, then they might get a weird error, but we can also check for that case probably in the Tables interface functions. I'll play around with this today.

**Comment by davidanthoff** [comment]
I think it would not be good it ``Tables.istable`` returned ``true`` in a case where the iterator then returned ``Int``s, that just seems like a bug to me. Also, what value would the trait provide at that point? The only thing I could rely on as a client is that something would iterate, but then you might as well just query the iterable trait in the first place.

**Comment by andyferris** [comment]
I’m thinking generators will appear in places where the user is already asserting that it is a table, so we don’t need to check `istable`. I don’t want my `Table` constructor to do one thing If the generator iterates sensible rows and something else (other than throwing an exception) if it iterates something else.

We wouldn’t care about generators that iterate entire columns, for example.

**Comment by quinnj** [comment]
Playing around with it here: https://github.com/JuliaData/Tables.jl/pull/31

**Comment by quinnj** [comment]
Fixed via https://github.com/JuliaData/Tables.jl/pull/60
