### ISSUE TITLE
wrapper for unknown schema, propertynames consistency

### ISSUE THREAD

**Issue by tpapp** [JuliaData/Tables.jl#33]
First, a question about the interface: for an iterator returned by `Tables.rows(table)`,
`propertynames(row)` for each `row` has to be the *same* `Tuple{Vararg{Symbol}}`, ie same symbols, *same order*?

So eg if `Tables.rows` returned `[(a = 1, b = 2), (b = 3, a = 4), (a = 5, b = 6, c = 7)]` would that violate the interface expectations?

Second, related question: if the above is correct, whenever `Tables.schema` returns `nothing`, a simple wrapper could obtain the first row, infer the schema, and then return that an also work as an iterable (provided, of course, that there is at least one row).

Asking because I would like to contribute the above wrapper, just wanted to clarify this.

**Comment by quinnj** [comment]
> First, a question about the interface: for an iterator returned by Tables.rows(table),
propertynames(row) for each row has to be the same Tuple{Vararg{Symbol}}, ie same symbols, same order?

Yes, this is currently assumed/expected in the interface.

> So eg if Tables.rows returned [(a = 1, b = 2), (b = 3, a = 4), (a = 5, b = 6, c = 7)] would that violate the interface expectations?

Yes to violating expectations, but in practice, this exact return object would probably work fine. It would first depend on what the "table" returned for `Tables.schema(x)` and second, if it returned `nothing` for the schema, most sink functions will iterate the first row and use the property names from that and then call `getproperty` for those property names on the rest of the rows. Not sure if that provides you any answers here.

> Second, related question: if the above is correct, whenever Tables.schema returns nothing, a simple wrapper could obtain the first row, infer the schema, and then return that an also work as an iterable (provided, of course, that there is at least one row).

Hmmmm.....yeah, this could maybe work. We essentially already have this with the [`Tables.buildcolumns(::Nothing, tbl)` definition](https://github.com/JuliaData/Tables.jl/blob/d06a6c44c3a1ba1049e4b453dbd3c50d637b2b33/src/fallbacks.jl#L94). It's not a wrapper, but just materializes in the unknown schema case. It could be interesting to see how a wrapper approach fares though.

**Comment by quinnj** [comment]
So I've been thinking a bit more about this and it's a little messy for a couple reasons:
* we essentially already have this functionality if you call `Tables.columns` on a row-oriented input source that has a schema of `nothing`, `Tables.buildcolumns` constructs a `NamedTuple` which has a schema
* the way table sources satisfy the interface, they define `Tables.rows(x::MyTable) = ...` themselves, so it's a bit tricky to "intercept" in that case and detect if they don't have a schema
* it would be problematic anyway to start iterating rows and assume the schema from the first row, not because of column names changing, but due to types. `Tables.buildcolumns` is mostly an exercise in building up columns, widening the types as necessary as we iterate through rows

So in short, I really don't see a clean way to integrate something like this into the current design, but we do, however, have a few solutions already in place; if you call `Tables.columns(x)` as a consumer, you don't have to worry about a schema-less scenario. In the row-oriented case, you could also call `Tables.rowtable(x)` or `Tables.rows(Tables.columns(x))` to run the table through "inference" essentially and get a schema.

One idea, however, would be to create something like:
```julia
struct RowsWithSchema{S, T, sch}
    firstiter::S
    rows::T
end

function rowswithschema(x)
    rows = Tables.rows(x)
    sch = Tables.schema(rows)
    firstiter = iterate(rows)
    if sch === nothing && firstiter !== nothing
        sch = Tables.Schema(propertynames(firstiter[1]), nothing)
    end
    return RowsWithSchema{typeof(firstiter), typeof(rows), sch}(firstiter, rows)
end

Base.IteratorEltype(::Type{RowsWithSchema{S, T, sch}}) where {S, T, sch} = S === Nothing ? Base.EltypeUnknown() : Base.HasEltype()
Base.eltype(rows::RowsWithSchema{S, T, sch}) where {S, T, sch} = typeof(rows.firstiter[1])
Base.IteratorSize(::Type{RowsWithSchema{S, T, sch}}) where {S, T, sch} = Base.IteratorSize(T)
Base.length(rows::RowsWithSchema) = length(rows.rows)

istable(::Type{<:RowsWithSchema}) = true
rowaccess(::Type{<:RowsWithSchema}) = true
rows(x::RowsWithSchema) = x
schema(x::RowsWithSchema{S, T, sch}) where {S, T, sch} = sch
materializer(x::RowsWithSchema) = rowswithschema

Base.iterate(x::RowsWithSchema{Nothing}) = nothing
function Base.iterate(x::RowsWithSchema, (i, st)=(1, x.firstiter[2]))
    i == 1 && return x.firstiter
    iter = iterate(x, st)
    iter === nothing && return nothing
    return iter[1], (i + 1, iter[2])
end
```
which would at least guarantee that the "rows iterator" returned had a schema w/ at least the propertynames. This would be convenient because if you use the `Tables.eachcolumn` pattern to access each value in a row, it works on both `Tables.Schema{names, types}` and `Tables.Schema{names, nothing}`.

**Comment by tpapp** [comment]
I still think that it would be great to clarify that a rows iterator that returns rows with different property names violates this interface. This is I guess implicitly assumed anyway by most users.

**Comment by quinnj** [comment]
I've added a note to the README for this
