### ISSUE TITLE
Can we make `ColumnTable` allow arbitrary dimenensions?

### ISSUE THREAD

**Issue by andyferris** [JuliaData/Tables.jl#37]
It seems to me that things like `(a = zeros(3, 3), b = fill(false, 3, 3))` would satisfy the requirements of a length-9 column table. For example, `TypedTables.Table` can be an `AbstractArray` of `NamedTuple`s of arbitrary dimensionality (matching the columns themselves). Do you think we could slightly expand the `ColumnTable` type?

**Comment by quinnj** [comment]
I don't really have grand plans for `columntable`; currently, the only hard definition is "NamedTuple of AbstractVectors"; are you saying that's too strict? I'm a tad hesitant to change it since it's really meant to just be something very simple and useful for testing/repl and nothing more serious. But if the required changes aren't too crazy, I'm open to supporting something else.

**Comment by andyferris** [comment]
The suggestion is simply "NamedTuple of AbstractArrays" rather than "NamedTuple of AbstractVectors" - I suspect there's nothing too crazy beyond that.

(To support higher-dimensional arrays throughout the ecosystem, we should make sure we support `size`, `HasShape{2}` and so-on consistently).

**Comment by quinnj** [comment]
ok, I think that'd be ok. care to submit a PR and we'll see what it looks like?
