### ISSUE TITLE
functional interface with records from file (stateful iterator)

### ISSUE THREAD

**Issue by tpapp** [JuliaData/Tables.jl#42]
I have an API design question. Suppose some data format stores information in a file like this:

```
magic
header
[opaque compressed stream of 
 record1
 record2
 record3
 ...]
```
where `header` specifies the schema, and `record`s are the rows. I want to implement the rows interface, so that rows are read on demand from a stream. A
```julia
struct MyTable
    schema
    position
end
```
could be created once the header is read, and the file position of the compressed stream is established, eg by
```julia
t = readmytable("some/path.bin")
```
Then the user could implement
```julia
rows = Tables.rows(t)
schema = Tables.schema(rows)
collect(rows) # or equivalent
```

The question is: if the iterator on `rows` is started again, what should happen? Should the file reseek to the initial position and do the reading again? Similarly, what should
```julia
Iterators.take(rows, 5)
Iterators.take(rows, 10)
```
do, should it reset to position?

If two such iterators are interleaved (eg with `zip`), this could lead to funny behavior.

Or, would it be OK if the interface enforced that you can call `iterate(rows)` once and only once, and all futher calls lead to an error?

**Comment by quinnj** [comment]
Sorry for such a delay in responding, this issue must have slipped through my email cracks somehow. All good questions. As far as I can tell, the iterator interface itself in Julia doesn't have hard requirements around whether iterators need to be "resettable" or not. I think generally, if they _can_ be reset, then they do, but there are certainly cases of iterators becoming "exhausted" and can't iterate anymore. For reference, in CSV.jl, I restructured the `CSV.File` type so that it provides a rough kind of "random access" to the underlying csv file; it does this by holding a reference to the raw bytes of the file and a vector of "row positions" that mark the byte offset of the start of each row. "Parsing" the csv file then becomes a task of first seeking to the start of the row, then to the, perhaps subset of, columns in the row.

I think the best approach is make your iterator as flexible as possible (by allowing it to reset if possible), or if not, or if it could potentially be prohibitive, to clearly document any limitations.

Feel free to re-open or follow up on any questions/comments here.
