### ISSUE TITLE
Tables.jl and JuliaDB: supporting tuple row tables

### ISSUE THREAD

**Issue by bkamins** [JuliaData/Tables.jl#6]
This is mostly to keep track of the possible problem.

In JuliaDB you can create a table without column names. Then its `eltype` is a `Tuple` not `NamedTuple`. Maybe you have an answer to what should be done in this case?

I have also opened a related issue here https://github.com/JuliaComputing/JuliaDB.jl/issues/220.

**Comment by andyferris** [comment]
Right... this is where things get rather interesting!

Where my thinking is at on this is if you can't assume much about the rows, then the best thing you can say is that you have a nested container - an interable of iterables. Perhaps even an interable of indexables, where `keys(first(table))` is the same as the `keys` of all the other rows.

It becomes a bit tricky to define a generic interface like this when you don't have many constraints or much knowledge to hook into. I suppose in the case the row is indexable, you could say `columns` is the "inverted" view of the `rows` of table, so that `first(rows(table))[column] == first(columns(table)[column])` (if both are indexable this is `rows(table)[i][j] == columns(table)[j][i]`). We could rename `columnnames` to `columnkeys` (or `columnindices` if Julia is going that way eventually).

(The "I known nothing" approach is exactly what is being attempted in [SplitApplyCombine.jl](https://github.com/JuliaData/SplitApplyCombine.jl), where there are relatively generic functions that might be useful data operations on `rows`, and where there is an `invert` function to go from a column to row view and back again).

**Comment by joshday** [comment]
I've discussed with @shashi about possibly disallowing tuples in JuliaDB and forcing namedtuples.  It would require small changes to a few constructors, but I don't think it would actually break anything, and we could simplify the internals in many places.

**Comment by quinnj** [comment]
I also discussed w/ @shashi and @jeffbezanson about the possibility of defining `getproperty(t::Tuple, i::Int)`, which would allow a valid `Row` type to be a plain tuple, which interestingly already returns:
```julia
julia> t = (:a, :b, :c)
(:a, :b, :c)

julia> propertynames(t)
(1, 2, 3)
```

**Comment by andyferris** [comment]
I suspect that might be because (IIRC) a tuple's field names are `1`, `2`, ....

**Comment by quinnj** [comment]
I've been adding support for using tuples as rows here and there and it should all work now. Please comment here or open another issue if you find issues.
