### ISSUE TITLE
istable catches too many types

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaData/Tables.jl#74]
Change in 5c897d5c57bd1420173a8ef24dfcc6a389222015 makes `istable` very generous for non table types.
E.g `istable(true)` or `istable(1)`  return true... Also `Tables.istable(Dict())` will return true! 
Doesn't it need to be at least `(Base.isiterable(T) && Base.isiterable(eltype(T)))`, or something like that?

**Comment by quinnj** [comment]
This was intentional. Here's an explanation of how things were before/after this was changed:
* Before: there were weird cases where a type could be `istable`, but not property implement the interface, leading to `ArgumentError`s being thrown in those invalid cases; there were also a number of types that could easily be considered tables but weren't (generators of namedtuples, Vector{Any} of namedtuples, etc.)
* After: we now will try to treat anything iterable as a table, but if the source doesn't iterate valid elements (NamedTuples or another property-accessible object), a, now more informative, `ArgumentError` will be thrown explaining why the source was invalid.

So overall, both before and after, there's a chance that calling `Tables.rows(x)` or `Tables.columns(x)` on something would throw `ArgumentError`, the error message has improved though. We are more liberal in what we initially allow in `istable`, but I'd like to deprecate `istable` entirely and just have packages call `Tables.rows(x)` and `Tables.columns(x)` as appropriate. If by chance the package can provide additional error context, then they're free to catch the `ArgumentError` and rewrap/reskin the error.

Anybody have any concerns w/ that approach?

**Comment by tpapp** [comment]
> Anybody have any concerns w/ that approach?

Imagine a function that supports ingesting from sources implementing various interfaces, including the interface `Table`.

If `istable` is picky, it can test for `Table` first and fall back to the other one. If `istable` is permissive, it has to catch an error, or test with `applicable(Table.rows, input)`, which are (IMO) less elegant. Or is the intention to use the latter?

**Comment by SimonDanisch** [comment]
Well, I thought I found the right trait/function to decide what to plot/display as a table :P 
I guess I should have informed myself before about what `istable` is meant to do - like this it's pretty useless for that purpose.
Is there any other function I can use to identify a `DataFrame`, `TypedTable`, any other random TableType as table type?

**Comment by SimonDanisch** [comment]
Ideally it shouldn't be a heuristic, but instead something like:
```julia
# Tables.jl
istable(x) = false

# DataFrames.jl
Tables.istable(x::DataFrame) = true

 # TypedTables.jl
Tables.istable(::TypedTable) = true
```
So that there is a guarantee for no false positives!

**Comment by quinnj** [comment]
@SimonDanisch, that was how `istable` worked originally, but then there were complaints that things that "satisfy the Tables interface" aren't considered tables, like generators of namedtuples. The heart of the issue here comes down to the awkwardness of objects _implicitly_ satisfying the Tables.jl interface, but not _explicitly_ opting in via defining `istable`.  The fact is we don't really know if something could be a table or not until we start iterating it. I mean, in an ideal world, we'd be able to define a more accurate fallback like `Tables.istable(x::Iterable{<:PropertyAccessible})`, but even then, not all iterables know their eltype, so there'd _still_ be cases we'd be excluding that are perfectly valid "tables".

For now, @tpapp is correct with the approach of "it has to catch an error". For reference, see the "catchall" DataFrames constructor here: https://github.com/JuliaData/DataFrames.jl/blob/master/src/other/tables.jl#L16. It basically employs this strategy (we could remove the `Tables.istable(x)` check) by checking for a few known cases that aren't easily dispatchable, then fallsback to just calling `Tables.columns(x)` on the input. If that throws an error, it's because the input actually doesn't satisfy the Tables.jl interface and DataFrames would just rethrow that error anyway (since it doesn't have any other options for trying ot convert something to a DataFrame).

**Comment by davidanthoff** [comment]
Here is my thinking on this, after having gone through the same design question with [TableTraits.jl](https://github.com/queryverse/TableTraits.jl). The relevant function in that ecosystem is called `isiterabletable`, and it plays the same role as `istable` here. I started out with a design similar to the one here, where that function returns a `Bool`. I pretty early came to the conclusion that that was a mistake because the function at that point is pretending that it can answer a question with yes/no, when it really can't. As @quinnj points out above, there are cases where you don't know whether something is a table or not just based on the type. If one wants a function that returns a `Bool`, one should name it `is_maybe_a_table`, that would be an accurate name.

I think there are two ways out: either take the [TableTraits.jl](https://github.com/queryverse/TableTraits.jl) route and introduce a third possible return value for the situation where one doesn't know whether something is a table or not, or just drop the whole idea of an `istable` function.

For [TableTraits.jl](https://github.com/queryverse/TableTraits.jl) I made the change to three possible returns values last September (I generally don't break things ever in Queryverse, so I actually queued this change for a long time so that it could coincide with the other breaking changes that came with the general julia 1.0 transition). So `isiterabletables` can return `true`, `false` or `missing`. That to me seems the correct semantics for this function. `missing` means that the trait function can't tell you whether a type is a table or not, you'll have to try to iterate it to find out.

I also thought about dropping the trait function entirely, but in the end decided against that. Two reasons: a) there are cases where it makes sense to go with a different client implementation for the `true` and `missing` case. They are not super common, but the pattern seems general enough to me that I think it warrants having that support. b) clients don't have to call `isiterabletable`, they can always just try to iterate and fail if the source is not a table, so having the trait function is not adding any complexity to clients relative to the no-traits function implementation.

Having said all of that, I think even in the existing Tables.jl design `istable` could have a better implementation that returns fewer false positives. Indeed, that was the case pre #60. [This](https://github.com/JuliaData/Tables.jl/pull/60/files/5f479dc7928c8107fda250d4dfeeb324aebdcc4a#diff-8ee45405132cf2e01d517fa4270dedcf) change I think was not an improvement on that front. I think a better implementation there shouldn't return `true` for iterables that have `HasEltype()` with a `eltype()` that is clearly not a row (like e.g. a number).

**Comment by SimonDanisch** [comment]
Would be great to separate the heuristic from an explicit overload.
So having `istable` & `maybetable` would be an improvement! 
Maybe we can do this with little interruption?
As it stands, it seems pretty weird to require packages that inherit the table trait to explicitly overload the heuristic to return true. It makes the information gained by the overload almost 0, since it likely would have already been true before (even if not, the new gained certainty wouldn't propagate to the caller of `istable`) ;)

**Comment by ablaom** [comment]
I must say these recent changes are causing me some headaches in MLJ, where we want a common interface for accessing rows of a wide variety of objects. 

If I want to select rows of an object, how can I tell if I should use the Tables.rows/Tables.cols (because, my object is a TypedTable, for example) or normal indexing (because my object is a Vector{Float64})? Both are now tables (according to `istable`) but both are also AbstractVectors.

**Comment by nalimilan** [comment]
AFAICT the biggest problem happens when you want to dispatch on whether an argument is a table or something else (like a vector), which is what @ablaom and @SimonDanisch need. For dispatch you need a clear yes/no answer.

Maybe we could at least have a clear trait for objects that implement the *row* interface (which would include named tuples)? Then it would at least be possible to know whether a given iterable is a table based on to its element type (or on the type of the first element if the element type is abstract -- at least for `AbstractArray`). That would allow distinguishing `Vector{Int}` from `Vector{<:NamedTuple}` and calling the appropriate function.

The other solution would be to introduce a special wrapper to signal objects that are tables when their type doesn't make this clear, like for `Array`. That wrapper would only be required for methods which rely on dispatch.

**Comment by ablaom** [comment]
Okay, I can distinguish between `Vector{Int}` and `TypedTable` using `Tables.rowaccess`. However, the `istable`, `rowaccess` and `columnsaccess` traits all coincide on `Vector{Int}` and `JuliaDB.IndexTable` objects. So is there a way to tell them apart (without `try`ing and `catch`ing errors)?

**Comment by piever** [comment]
From what I understand, this is mainly an issue is when one tries to write a function that can take both table-like and non table-like input. I was thinking whether this could be fixed by writing a "lazy table wrapper", so that `Table(t)` is a declaration that `t` is table-like (but it doesn't collect rows or columns). For example, in the case of StructArrays, as the package is not specifically about tables, I'd be uncomfortable  adding a `istable` condition on the `::Any` fallback (it would also ruin inferrability of the constructor), but  it sounds more reasonable to add a `::Table` method. Similarly [StatsMakie](http://juliaplots.org/StatsMakie.jl/latest/manual/tutorial/#What-if-I-have-data-instead?-1) needs to use an explicit wrapper (there it's called `Data`) so that it can dispatch on it.

**Comment by clarkevans** [comment]
I think there are two things going on here: (a) an explicit many-to-many interface that modules could implement so they could be interoperable; (b) some clever guessing for table-like native objects. I'd like the former, but not the latter.  Could these be split apart?  For the latter, perhaps something like `Table` as suggested by @piever. 

I am asking `Tables` to help my data processing library integrate with `CSV` and `DataFrame` and other table-like objects without creating direct dependencies on those modules. That said, what I expressly don't want help with is wrapping native Julia objects, since I have my own conversions for those that are idiosyncratic.  Specifically, I don't even want a vector-of-tuples to be handled for me.  

Here is just one example of something I didn't expect to be a table.

```
julia> Tables.istable((this = [(isa = "table?",)],))
true

julia> Tables.schema((this = [(isa = "table?",)],))
Tables.Schema:
 :this  NamedTuple{(:isa,),Tuple{String}}

julia> Tables.columns((this = [(isa = "table?",)],))
(this = NamedTuple{(:isa,),Tuple{String}}[(isa = "table?",)],)
```

I think that considering anything that is iterable to be a table is problematic.

**Comment by clarkevans** [comment]
> I'd like to deprecate istable entirely and just have packages call Tables.rows(x) and Tables.columns(x) as appropriate

Given the current behavior, yes, it should be deprecated.  The most important thing, in my opinion, is to update the README so that implementer don't have to spend time on it.  It took me several hours, once a week ago, and now even, looking back trying to verify compliance with `Tables.jl`.

I suppose if the recommendation is to raise `ArgumentError` if something isn't a table, then perhaps there's a bunch of edge case work in the core `Tables.jl` code to work though?

```
julia> Tables.columns([(nothing,)])
ERROR: TypeError: in NamedTuple, in name, expected Symbol, got Int64
Stacktrace:
 [1] NamedTuple{(1,),T} where T<:Tuple(::Tuple{Array{Union{},1}}) at ./boot.jl:531
 [2] buildcolumns(::Nothing, ::Tables.IteratorWrapper{Array{Tuple{Nothing},1}}) at /home/cce/.julia/packages/Tables/qIlOP/src/fallbacks.jl:130
 [3] columns(::Array{Tuple{Nothing},1}) at /home/cce/.julia/packages/Tables/qIlOP/src/fallbacks.jl:154
 [4] top-level scope at none:0
```

**Comment by quinnj** [comment]
Ok, I've been noodling on this for a day or two now. The only immediately solution I've come to is restricting `istable` again, while leaving the generic fallbacks for `Tables.rows`/`Tables.columns`. That at least gives the scenario where `istable` isn't too permissive and only returns `true` for known, actual Tables.jl-compatible sources, while also allowing packages that want to be more permissive to just call `Tables.rows`/`Tables.columns` and try-catch errors if desired.

**Comment by SimonDanisch** [comment]
Thanks @quinnj, that intuitively sounds like the right way to do it!
When duck typing and not caring about the type - you just try to use the functions you care about and see how it goes.
When you really want to know if you have a table type, you call `istable` :)

**Comment by clarkevans** [comment]
Yes, a conservative interface would be fantastic. This would enable a choice among packages: (a) use duck typing, and deal with exceptions, or (b) look-before-you-leap, where exceptions are actually errors.  

I think it might be OK, and perhaps helpful for some, if Table.jl would like to expressly mark and provide built-in support for a vector-of-tuples. A specific package like ours could always dispatch based upon  `RowTable` before going though Table.jl fallback logic since we don't consider a vector-of-tuples to be a Table.  So, what ever core types you consider tables, could they be documented so that exceptions could be maintained?

**Comment by davidanthoff** [comment]
Why not just adopt the TableTraits.jl semantics?

**Comment by clarkevans** [comment]
David: I'm not sure I understand the value proposition of the 3-way switch.  For a given object (or type), it seems to me that library either provides `Tables.jl` compliance or it doesn't.  Are you saying that `maybe` is for types, where some of the values are `false` and some are `true`?  Do you have concrete use cases that justify this more sophisticated model? Certainly finer-grained models could be useful in some cases, but they increase implementation costs for both the protocol and the libraries that use it.

**Comment by davidanthoff** [comment]
There are cases where one cannot tell whether something is a table or not based on the type. The canonical example is a generator. It might be a table or not, depending on what it will end up iterating, but you cannot know what you'll get before you start iterating. It seems to me that in those cases the semantically correct answer for a function like `istable` is "I don't know, maybe", because both "yes" or "no" are simply incorrect. And generators are _not_ corners cases. Any [Query.jl](https://github.com/queryverse/Query.jl) query for example can also end up in this category.

**Comment by clarkevans** [comment]
Could the interface remain simple by keeping `istable` a binary question -- at _instance_ level only?

Is there a benefit to having `istable` (when it could possibly be `maybe`) at the type level?

**Comment by quinnj** [comment]
Here's where my thinking has come:

* It seems clear there are examples, I'm assuming from at least @clarkevans and @SimonDanisch, where there's a desire to only work w/ `Tables.rows`/`Tables.columns` where it's guaranteed to work, i.e. known cases of a source that has properly implemented the interface
* I also assume that, for their cases, in the situation that `istable(x) === false`, they have an alternative path they wish to take; throwing their own error, trying their own alternative approaches to whatever plots/ml thing they're trying to do, etc. Included in this assumption is they're not as concerned about users passing in `Vector{Any}` or Generators of NamedTuples that **could** be perfectly valid tables, but it's not really sure, so they're willing to not worry about those cases or rely on users collecting/transforming to a real Tables.jl input properly.
* I think there are other cases like `CSV.write`, where, as the package author, I don't really care whether `istable(x) === true` explicitly, and I'm willing to just call `Tables.rows(x)` and see if it works. If it fails, I'm fine w/ the error being throw, because there isn't really another alternative to try. If I wanted to be extra thorough, maybe I wrap `Tables.rows(x)` in a try-catch, and then throw my own error with some extra details to help the user write out a csv file

Give those two main use-cases, I don't see the TableTraits.jl 3-value approach adding a lot of value. In the first case, they're only interested in `istable(x) === true` and have alternative solutions otherwise. In the second case, I'm willing for an error to be thrown anyway, so I don't even bother calling `istable`.

Maybe there's a third use-case where someone potentially wants to: 1) call `istable` and if `true`, immediately call `Tables.rows`/`Tables.columns` and do Tables.jl thing, 2) if `istable(x) === false`, go down some alternative path, trying something else, maybe eventually fail, and 3) if `istable(x) === missing`, as a final-final last resort, do a try-catch on `Tables.rows`/`Tables.columns`. In that case, the TableTraits.jl scenario would be preferable, since you just call `istable(x)` once and can "switch" based on the result. I'm just not sure how common this third option really is (if at all), and where "dispatch solutions" (i.e. just having separate methods that can catch valid/invalid cases explicitly via dispatch) actually don't work. At least for DataFrames, the only cases where things get really tricky are `Vector{Any}`, where you're not sure what's inside an array and can't really tell how to make a DataFrame unless you start looking at each element.

**Comment by quinnj** [comment]
Ok, PR up: https://github.com/JuliaData/Tables.jl/pull/84

**Comment by clarkevans** [comment]
Jacob,  I'm liking where this is landing. You've articulated my perspective. I think David's feedback that some types, as a class, simply don't know if they are a table or not also reflects my understanding of the problem space. The real determination if an object is a table could probably be done at the instance level?  If this is the case, it might be helpful if `istable` could only be defined at the instance level.  This might reduce the learning curve and implementation questions for those using the interface. For example, some users of the library might accidentally see that the type-level check says `false` and then assume it applies to all instances.  Cheers, Clark

**Comment by quinnj** [comment]
No, the problem is that even at the instance level, you can't really know something is a table or not. You could have a `Any[(a=1, b=2), (a=3, b=4)]`, which has type `Vector{Any}`, but iterates NamedTuples and is a perfectly valid "Row iterator" as defined in the Tables.jl interface. Generators also fall into this camp, where you can't really know the element types (sometimes) until you start iterating.

Before the next release, I'll definitely do another pass on the documentation and code comments to help clarify some things.

**Comment by clarkevans** [comment]
So, I'm not opposed to David's solution.  It just won't help with my consumption of tables. I'm asking if the given type provided a reliable `Tables.jl` adapter to this particular object that will likely succeed (or it's an actual bug that the user, and neither library author, need be fixing).  This way I could provide alternative fallback conversions.

On the other hand, for the objects my system produces, I could know on an instance level if it could be converted reliably and could mark that accordingly.  But, at the type level, I couldn't make any guarantees, so, this would be be left unset. I could do a best-effort conversion for those that leap before they look, but boy it might be ugly. 

Perhaps we need 2 valued logic, but it reflects "certain" support then, at either the type or 
instance level?  `Union{Val{:Supported},Missing}` ?

**Comment by quinnj** [comment]
`istable` already supports being called at the type-level or at the instance level, so if you know at the instance level, then define that and all should be good. **Users** of `istable` should always call at the instance level.

**Comment by tpapp** [comment]
> Users of istable should always call at the instance level.

Perhaps clarify and emphasize this somewhere, eg in the docstring of `istable`, and the README?

**Comment by clarkevans** [comment]
Thank you so much.  This solves the problem with `istable` catching too many types.
