### ISSUE TITLE
Enhanced Tabular API

### ISSUE THREAD

**Issue by Nosferican** [JuliaData/Tables.jl#80]
One reason that prevents me from writing more generic code is that I rely on various utilities not supported uniformly by the current API. For example, filtering may be done generically through Query.jl which uses IterableTables. Is that the preferred approach? Things like reshaping and split/apply operations currently are hard to conciliate with generic tables. What would be the optimal solution to this?

**Comment by nalimilan** [comment]
Similar to https://discourse.julialang.org/t/common-api-for-tabular-data-backends/21546

**Comment by davidanthoff** [comment]
@Nosferican you should also be able to do split/apply with [Query.jl](https://github.com/queryverse/Query.jl) (using `@groupby` and `@map`), and reshaping a la gather and spread is in the works right now (we have a PR for a `@gather` macro, spread will follow later), and it all works for any table type.

The underlying tech is not related to IterableTables.jl, but the generic tables interface defined in TableTraits.jl. Most Tables.jl sources/sinks _also_ implement the TableTraits.jl interface, and that is why it works fairly smoothly.

**Comment by Nosferican** [comment]
Great to learn that. I will explore how to transition from a DataFrames to using Query with a tabular source soon. For example, Query-like for `dropmissing(data, disallowmissing = true)`. Any quick way to do something like any value in that row has a `missing` (didn't see an example of such in the docs). It seems Query doesn't play nice right now with Terms 2.0 so it might require patching a thing or two unless a branch already does this.

**Comment by davidanthoff** [comment]
Probably best to open issues for these things over at Query.jl, they don't seem related to Tables.jl at this point.

On the Terms 2.0, it should all work once https://github.com/queryverse/IterableTables.jl/pull/91 is merged.

**Comment by quinnj** [comment]
Sorry, I somehow missed this issue. Yes, @Nosferican, currently Tables.jl is focused on providing a common API for how to access generic table backends data via row-wise access or column-wise access. It currently provides the `Tables.transform` and `Tables.select` operations, but mainly because they're very simple, highly demanded, and easy to make lazy w/ the Tables.jl api. I also don't see the Tables.jl package as a great long-term home for operations.

On the other hand, Tables.jl was very much designed with complete Query.jl integration in mind. So even if a Tables.jl source doesn't explicitly implement `getiterator`, you can always do `Tables.datavaluerows(x)` on any Tables.jl-compatible source to get a Query.jl-compatible DataValue-based NamedTuple iterator that can be used in any of the Query.jl macros/operations. 

Similarly, if you want to take any Query.jl "output" and send it to a Tables.jl-using sink function, you can do `Tables.IteratorWrapper(output)` and it will "unwrap" any DataValues on the way out of Query.jl.

This integration probably hasn't been publicized as well as we could (it's also been maturing, so probably has been good to let things mature), so if there are any suggestions to make this integration easier to use, I'm open to ideas.

**Comment by quinnj** [comment]
Ok, I updated the Tables.jl docs in https://github.com/JuliaData/Tables.jl/commit/5eced11b826e6ba5b0d355e7cfa55c847111a964 and included notes about `Tables.datavaluerows` and `Tables.nondatavaluerows`, which will at least be a breadcrumb for folks looking to integrate w/ Query.jl. I'm closing this for now, but feel free to ask any additional questions or clarifications here.
