### ISSUE TITLE
Why is `Tables.schema` needed?

### ISSUE THREAD

**Issue by clarkevans** [JuliaData/Tables.jl#86]
It seems that `CSV` doesn't  implement `Tables.schema` [currently](https://github.com/JuliaData/CSV.jl/issues/404).  Furthermore, the main example on how to make a sink avoids the use of `schema`:

```
function MyTable(x)
    Tables.istable(x) || throw(ArgumentError("MyTable requires a table input"))
    cols = Tables.columns(x)
    # here we use Tables.eachcolumn to iterate over each column in a `Columns` object
    return MyTable(collect(propertynames(cols)), [collect(col) for col in Tables.eachcolumn(cols)])
end
```

Here we see a recommendation not to use `schema`, but to use `propertynames` and `eachcolumn`.  Furthermore, I don't see where `eachcolumn` calls `Tables.schema` on the column object returned. 

Given that both the production and consumption of a `schema` are not actually used in practice, is there a reason for the `schema` function? Perhaps it might be useful for documenting *before* conversion, but, alas it's defined to work on the `columns` object produced after a conversion.  So, I'm not sure what purpose it serves.  It certainly confused me.

**Comment by quinnj** [comment]
Sorry for the confusion! The schema is indeed used by `eachcolumn`, as can be seen [here](https://github.com/JuliaData/Tables.jl/blob/master/src/utils.jl#L46). `eachcolumn` generates a method based on a run-length encoding of the input types to try to ensure a type stable inner loop when reading an input table. This is particularly important when collecting "rows", since for each row we iterate over, we then have to loop over each column within the row to get each value.

You are correct that the second definition of `eachcolumn`, which is used on "columns", does not use `Tables.schema`. When collecting columns, we're only doing a single loop the entire column set, which has drastically different performance concerns when compared to the row case.

Hopefully that helps clarify things.
